 
module.exports = 
{
	name: 'alpha',
	description: 'Alpha',
    execute(message) 
    {
        let questions = 
        [
            'Sollevare un secchio di tegole ',
            'Nel nuovo progetto di Dyrr sarà presente un automatismo che permetterà di ',
            'GDR-online ha pubblicato un interessantissimo approfondimento su ',
            'Un prestavolto non è mai mainstream, se gli aggiungi ',
            'Amministrare Tato e Nick è peggio che ',
            'La nuova razza di Dusk ha il potere di ',
            'Registrazione completata. La tua password è ',
            'Oggi su giocatoridiruolo.com è apparso un interessantissimo articolo su ',
            'Sono lento ma compenso con ',
            'Un pg da UF non è completo senza una laurea in ',
            'Se sono online significa che posso ',
            'Finalmente ho capito, il sistema di combattimento di IGI funziona grazie a ',
            'Chiudiamo per ',
            'Vorrei un pg atipico... Qualcosa tipo ',
            'Mi piacciono le razze non convenzionali, vorrei tanto giocarmi ',
            'Rivoluzionerò Ultima Spiaggia. Loggherò e giocherò ',
            'Ma è mai possibile che ovunque mi registri trovo ',
            'Chi non bleeda in compagnia, non è figlio di ',
            'Come siamo arrivati a pagina 34 in 48 ore? ',
            'Per approvare il BG del mio personaggio serve ',
            'Svelato il mistero della scomparsa di Outlaw, non ha retto il peso di ',
            'Mio malgrado, mi vengono passati ',
            'l\'apertura di fomoria è stata ritardata di altri 6 mesi, Steam vuole inserire anche ',
            'Per entrare nel forum segreto serve ',
            'Tanith sarebbe stata una grande land se non fosse stato per ',
            'Il nuovo progetto di Gerry si concentra su ',
            'Il sistema economico della nuova land di GoT si basa su ',
            'La prima regola di Chimaera è non parlare di Chimaera, la seconda regola di Chimaera è ',
            'Nell\'ultimo capito di AfterLife il mio pg si occupa di ',
            'Su Urban Legends ho molto bleedato a causa di ',
            'Verdux mi ha offerto un caffè per propormi ',
            'BunnyBoo ha creato una nuova Land e nel mercato ha inserito ',
            'Ho decifrato l\'ultimo post di J.G. e ho finalmente capito che parlava di ',
            'Feudo del ',
            'Al posto dei dadi avremo ',
            'Il lavoro prevede pagamento? NO. Requisiti richiesti: ',
            'Bevo per dimenticare ',
            'La prossima potteriana sarà "Harry Potter e la camera di ',
            'E su questo siamo d\'accordo, tuttavia',
            'VtM è un gioco',
            'Al posto della foto del PV nell\'avatar c\'era',
            'Daria stavolta si è presa una pausa da ',
            'Ma quindi cosa si gioca in questa land? ',
            'Per risollevare i pbc servirebbe una land a tema ',
            'La land fu completamente rovinata da ',
            'Un\'estate caldissima, un autunno ',
            'Ho trovato un prestavolto perfetto, si tratta di ',
            'Nella mia land inserirò la resurgo tramite ',
            'Nel mio background, i genitori del mio pg sono stati uccisi da ',
            'Sto preparando una moderna ma con l\'aggiunta di ',
            'La land esiste dai tempi di ',
            'Nel nostro gioco non ammettiamo ',
            'La polizia postale è impazzita quando nella cronologia del mio browser ha visto ',
        ];

        let answers = 
        [
            'gli screen della cricca recuperati da Razzi',
            'mettersi un cazzo in fronte e fare l\'uniporno',
            'unicorni borseggiatori',
            'Ariel nera',
            'Quetz',
            'avere il senso della misura di Presidenttk',
            'la parità dei sessi nelle land storiche',
            'i biscotti degli orfani di The Smoke',
            'i picciotti di Don Carmelo',
            'il pacco di The King',
            'la pesca dei dildi',
            'la gilda degli artisti',
            'sgallettata e mannara',
            'i dildi al mercato',
            'i permessi di morte',
            'la principessa monouso',
            'iridi ghiaccee',
            'giocare in alpha test',
            'NickNightingale che dopo 4 pagine di thread compare chiedendo un riassunto',
            'pane e banane',
            'il romanzo di Perla Stibbert',
            'le perdute che non riescono a giocare per mancanza di maschi vogliosi',
            'cavalleria pesante nei boschi',
            'autodidatta',
            'le spie sorde',
            'il turbosfigometro',
            'disegnare peni con paint',
            'forum parallelo in cui si discute su come far crollare le land',
            'introspettare',
            'la carrozzina di Steven',
            'trombing',
            'il disegnatore di peni',
            'i tornelli',
            'Max Rossi',
            'Adele',
            'i tornelli',
            'quattro turbosfigati, che sputtanati, si sentono tanto toccati da affrettarsi a riempire 30 pagine di unghie raschiate contro lo specchio',
            'le rubinee',
            'un drow albino',
            'il grande amore tra una fata e un demone',
            'la pornoelfa',
            'roma città aperta, sciuscià, the smoke',
            'giocare trame che hanno la durata di un contratto da stagista e la stessa inculata finale',
            'una land di Bunny a caso (senza peni)',
            'il gioco politico a colpi di cazzo',
            'cogestire con AnthonyRockets',
            'furtivo come Malagola',
            'un personaggio bambino che cuce palloni',
            'ammettere che Urban Legends è un diceless mascherato',
            'irrimediabilmente donna'
        ];

        var randomqs = questions[Math.floor(Math.random()*questions.length)];
        var randomans = answers[Math.floor(Math.random()*answers.length)];

		message.channel.send(randomqs + randomans);
	},
};
